### ISSUE TITLE
Assembly name lowercasing

### ISSUE THREAD

**Issue by AndreyKrupskiy** [Sitecore/Sitecore-Diagnostics-Tool#16]
As I can see, the GetResources method of Sitecore.DiagnosticsTool.Tests.UnitTestsHelper.Resources.SitecoreInstance class adds assemblies to a dictionary using lowercased assembly name as key. However, when running tests against support packages the key is not lowercased. The behavior in those two cases must be aligned.

**Comment by AlenPelin** [comment]
Fixed in `develop` branch, please check.
