### ISSUE TITLE
Tool is crashing during diagnostic preparation

### ISSUE THREAD

**Issue by thomasisler** [Sitecore/Sitecore-Diagnostics-Tool#4]
[log.20170703-073515.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1118488/log.20170703-073515.txt)

**Comment by AlenPelin** [comment]
Is it SSPG package or live Sitecore instance? Does it use Configuration Roles?

**Comment by thomasisler** [comment]
This is a "live" instance on a dev machine. What do you mean by "Configuration Roles"?

**Comment by AlenPelin** [comment]
Please provide config files.

I mean [Sitecore Configuration Roles](https://github.com/Sitecore/Sitecore-Configuration-Roles).

**Comment by thomasisler** [comment]
It's a Sitecore 7.2 installation. Since some config file contain customer related information I cannot provide them all. Are there specific config-files you're interested?

**Comment by AlenPelin** [comment]
The <sc.variable name="dataFolder" ... /> and <setting name="logFolder" ... />. 

It would be better however to take a look at the actual configuration files as is - for security concerns you can open official Support ticket, attach files to it and ask to direct it to me: "Please pass this ticket to Alen Pelin in regards https://github.com/Sitecore/Sitecore-Diagnostics-Tool/issues/4".

**Comment by AlenPelin** [comment]
Feel free to reopen ticket if you have any updates on it.
