### ISSUE TITLE
Sitecore Diagnostics Tool shows a lot of warnings for Configuration Pipelines consistency for CD role

### ISSUE THREAD

**Issue by vdeschamps** [Sitecore/Sitecore-Diagnostics-Tool#5]
I'm installing a Content Delivery node, and accordingly, to Sitecore guidelines says that some CONFIG files must be disabled.

As I've done it manually, I was expecting that Sitecore Diagnostics Tool would check it, and in fact, it did. However, now I'm seeing a lot of warnings and don't know if would be safe to ignore.

1. Launched Sitecore Diagnostics Tool
2. Choose the Local Sitecore instance
3. Marked on "Selected instance is" these boxes Content Delivery and Production
4. Marked on "Selected test categories" these boxes General, Security Vulnerabilities, Performance and Scalability, and Search and Indexing

```
The pipelines/initialize configuration pipeline definition data was changed: •Sitecore.PathAnalyzer.Pipelines.Initialize.Loader, Sitecore.PathAnalyzer

◦Missing

•Sitecore.Pipelines.Loader.CheckWebDAVConfiguration, Sitecore.Kernel

◦Missing

```
Any ideas why is this happening?

[scsupport_sc81u0-cd_201707181113.zip](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155668/scsupport_sc81u0-cd_201707181113.zip)
[log.20170718-081129.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155669/log.20170718-081129.txt)
[log.20170718-081200.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155670/log.20170718-081200.txt)

**Comment by vdeschamps** [comment]
[log.20170718-081200.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155657/log.20170718-081200.txt)
[log.20170718-081129.txt](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155658/log.20170718-081129.txt)

**Comment by vdeschamps** [comment]
[scsupport_sc81u0-cd_201707181113.zip](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1155662/scsupport_sc81u0-cd_201707181113.zip)

**Comment by AlenPelin** [comment]
Hey @vdeschamps, thanks for taking time to report this issue. I'm afraid this test only designed to compare current configuration with default - so only valid for standalone installation (default configs). In the next version this test will be either fixed or removed.
