### ISSUE TITLE
Validates Role Specific Configurations

### ISSUE THREAD

**Issue by klpatil** [Sitecore/Sitecore-Diagnostics-Tool#9]
Hello Alen,

I have quick question for you. Current SDT Validates Role Specific configurations are applied or not? as per https://doc.sitecore.net/sitecore_experience_platform/setting_up_and_maintaining/xdb/configuring_servers/configure_a_content_management_server

If yes - Then great. If Not, Then you are working on it or someone else is working on it? If not - Then I would like to contribute do you think it will add value?

Thank you for such a nice tool,
Kiran

**Comment by AlenPelin** [comment]
It doesn't exist, but it is in progress now, ETA in October.

**Comment by klpatil** [comment]
Great - Let me know If I can be of any help

**Comment by AlenPelin** [comment]
Until then I recommend to use Configuration Roles as it makes this whole thing unnecessary :)

**Comment by klpatil** [comment]
Yeap -- I agree and aware -- Thanks for thought. But I have to validate environment which is already setup and ready to go live

**Comment by AlenPelin** [comment]
Well, in this case there is a workaround - use configuration roles to get you showconfig.xml for all necessary roles. Compare these showconfig.xml using WinMerge to your actual solution.

**Comment by klpatil** [comment]
Genius - Will give it a try - Thank you @AlenPelin!

**Comment by AlenPelin** [comment]
With Sitecore 9.0 release this no longer makes sense, #28 was registered instead.
